// vue/src/components/GameTile.vue
<template>
  <div
    class="tile"
    :class="[
      `tile__${props.tile.label}`,
      `tile__${props.tile.flipped ? 'flipped' : 'masked'}`
    ]"
    @click="emits('flip', tile.x, tile.y)"
  >
    <span>{{ tile.label }}</span>
  </div>
</template>

<script setup lang="ts">
import { Tile } from '../../../common/model';

const props = defineProps<{
  tile: Tile
}>()

const emits = defineEmits<{
  flip: [x: number, y: number]
}>()
</script>

<style scoped>

</style>

// react/src/GameTile.tsx
import { Tile } from "../../common/model";
import React from "react";

export type GameTileProps = {
  tile: Tile,
  flip: (x: number, y: number) => void
}

export function GameTile({ tile, flip }: GameTileProps) {

  console.log(tile)

  return (
    <div
      className={`tile tile__${tile.label} tile__${tile.flipped ? 'flipped' : 'masked'}`}
      onClick={() => flip(tile.x, tile.y)}
    >
      <span>{ tile.label }</span>
    </div>
  )
}

export const GameTileMemo = React.memo(GameTile)
