// vue/src/components/GameBoard.vue
<template>
  <div
    id="board"
    :style="boardConfig">
    <GameTile
      v-for="tile in tiles"
      :tile="tile"
      :key="tile.key"
      @flip="handleFlipTile">
    </GameTile>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { Board } from '../../../common/model';
import GameTile from './GameTile.vue';

const size = ref(12)
const bombs = ref(12)
const board = ref(new Board(size.value, bombs.value))

const boardConfig = computed(() => ({
  gridTemplateColumns: `repeat(${size.value}, 1fr)`,
  gridTemplateRows: `repeat(${size.value}, 1fr)`
}))

const tiles = computed(() => Object.values(board.value.tiles))

function handleFlipTile(x: number, y: number) {
  board.value.flip(x, y)
}
</script>

<style scoped>

</style>

// react/src/GameBoard.tsx
import { useCallback, useEffect, useMemo, useState } from "react"
import { Board, Tile } from "../../common/model"
import { GameTile, GameTileMemo } from "./GameTile"

export function GameBoard() {
  const [size] = useState(12)
  const [bombs] = useState(12)
  const [tiles, setTiles] = useState<Tile[]>([])

  const board = useMemo(() => new Board(size, bombs), [])

  useEffect(
    () => setTiles(Object.values(board.tiles)),
    []
  )

  const flip = useCallback((x: number, y: number) => {
    board.flip(x, y)
    setTiles(Object.values({...board.tiles}))
  }, [board])

  return (
    <div
      id="board"
      style={{
        gridTemplateColumns: `repeat(${size}, 1fr)`,
        gridTemplateRows: `repeat(${size}, 1fr)`
      }}>
        {
          tiles
            .map(t => <GameTile
              tile={t}
              key={t.key}
              flip={flip}/>)
        }
    </div>
  )
}
